services:
  backend:
    build: backend
    ports:
      - 8080:8080
      - 8443:8443

  frontend:
    build: frontend
    ports:
      - 8443:443
      - 8080:80
    volumes:
      - ./frontend/etc/ssl:/etc/nginx/ssl
    restart: always
    depends_on:
      - backend