services:
  backend:
    build: backend
    networks:
      - app-network
    ports:
      - 8443:8443
      - 8080:8080
  frontend:
    build: frontend
    restart: always
    ports:
      - 443:443
    networks:
      - app-network
networks:
  app-network: