export namespace MathExerciseSubType {
  export enum SingleResultOperation {
    ADDITION = 'ADDITION',
    DIVISION = 'DIVISION',
    MULTIPLICATION = 'MULTIPLICATION',
    SUBTRACTION = 'SUBTRACTION',
    NUMBERCOMPLETION = 'NUMBERCOMPLETION',
    TENSCOMPARISON = 'TENSCOMPARISON',
    DOUBLING = 'DOUBLING',
    HALVING = 'HALVING',
    COMPARISON = 'COMPARISON',
    THREESTEPADDITION = 'THREESTEPADDITION',
    THREESTEPSUBTRACTION = 'THREESTEPSUBTRACTION',
    ROUNDINGTEN = 'ROUNDINGTEN',
  }

  export enum NeighborOperation {
    NEIGHBORS = 'NEIGHBORS',
  }

  export enum SortingOperation {
    SORTING = 'SORTING',
    ORDEROFOPERATIONS = 'ORDEROFOPERATIONS',
  }

  export enum TableOperation {
    MULTIPLICATIONTABLE = 'MULTIPLICATIONTABLE'
  }

  export enum LongOperations {
    LONGADDITION = 'LONGADDITION',
    LONGSUBTRACTION = 'LONGSUBTRACTION',
    LONGMULTIPLICATION = 'LONGMULTIPLICATION',
  }
}
